services:
  web:
    build: .
    container_name: safe_ideas_bot
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8000"